// Diccionario ES/EN. Los textos admiten {placeholders} y **negrita**.
export const STR = {
  // ── Navegación / chrome ──
  'nav.bracket': { es: 'Cuadro', en: 'Bracket' },
  'nav.groups': { es: 'Grupos', en: 'Groups' },
  'nav.favourites': { es: 'Favoritos', en: 'Favourites' },
  'nav.accuracy': { es: 'Precisión', en: 'Accuracy' },
  'nav.how': { es: 'Cómo funciona', en: 'How it works' },
  'nav.report': { es: 'Informe', en: 'Report' },
  'title.report': { es: 'Informe final', en: 'Final report' },
  'title.bracket': { es: 'Cuadro proyectado', en: 'Projected bracket' },
  'title.groups': { es: 'Fase de grupos', en: 'Group stage' },
  'title.favourites': { es: 'Favoritos al título', en: 'Title favourites' },
  'title.accuracy': { es: 'Precisión del modelo', en: 'Model accuracy' },
  'title.how': { es: 'Cómo funciona', en: 'How it works' },
  'title.sub': { es: '· Mundial 2026', en: '· World Cup 2026' },
  'common.loading': { es: 'Cargando…', en: 'Loading…' },
  'common.champion': { es: 'Campeón más probable', en: 'Most likely champion' },
  'app.connecting': { es: 'Conectando con el servidor… (puede tardar si estaba en reposo)', en: 'Connecting to the server… (may take a moment if it was asleep)' },
  'footer.disclaimer': { es: 'Datos oficiales reales · proyección estadística, no pronóstico oficial', en: 'Real official data · statistical projection, not an official forecast' },
  'footer.model': { es: 'Elo + Poisson · {n} partidos', en: 'Elo + Poisson · {n} matches' },

  // ── Header ──
  'header.dataThrough': { es: 'Datos hasta {d}', en: 'Data through {d}' },
  'header.updating': { es: 'Actualizando…', en: 'Updating…' },
  'header.checking': { es: 'Buscando datos nuevos', en: 'Checking for new data' },
  'header.updated': { es: 'Actualizado {when}', en: 'Updated {when}' },
  'header.autoUpdate': { es: 'Se actualiza automáticamente', en: 'Updates automatically' },

  // ── Banner del cuadro ──
  'banner.realTitle': { es: 'Cuadro real vs predicho', en: 'Real vs predicted bracket' },
  'banner.realKo': { es: 'eliminatorias: **{n}/{tot}** partidos jugados.', en: 'knockouts: **{n}/{tot}** matches played.' },
  'banner.realDesc': { es: 'Los cruces y resultados son los **reales**; donde aún no se ha jugado, avanza el favorito del modelo (›).', en: 'Matchups and results are the **real** ones; where not yet played, the model favourite advances (›).' },
  'banner.projTitle': { es: 'Proyección con datos reales', en: 'Real-data projection' },
  'banner.projDesc': { es: '{n} jugados, {r} simulados. En cada cruce **avanza el favorito** (›).', en: '{n} played, {r} simulated. In each tie **the favourite advances** (›).' },
  'banner.tap': { es: 'Pulsa un partido para la predicción.', en: 'Tap a match for the prediction.' },
  'legend.hit': { es: 'cruce acertado', en: 'matchup hit' },
  'legend.miss': { es: 'cruce fallado', en: 'matchup miss' },
  'legend.played': { es: 'jugado', en: 'played' },
  'legend.pens': { es: 'penaltis', en: 'penalties' },
  'legend.qualified': { es: 'clasificado', en: 'qualified' },
  'legend.undecided': { es: 'depende', en: 'undecided' },

  // ── Rondas ──
  'round.r32': { es: '16avos', en: 'Round of 32' },
  'round.r16': { es: 'Octavos', en: 'Round of 16' },
  'round.qf': { es: 'Cuartos', en: 'Quarter-finals' },
  'round.sf': { es: 'Semis', en: 'Semi-finals' },
  'round.sfLong': { es: 'Semifinales', en: 'Semi-finals' },
  'round.final': { es: 'Final', en: 'Final' },

  // ── Bracket ──
  'bracket.view': { es: 'ver predicción', en: 'view prediction' },
  'bracket.played': { es: 'ya jugado', en: 'already played' },
  'bracket.zoomOut': { es: 'Alejar', en: 'Zoom out' },
  'bracket.zoomIn': { es: 'Acercar', en: 'Zoom in' },
  'bracket.zoomFit': { es: 'Ajustar a la ventana', en: 'Fit to window' },
  'bracket.scoreReal': { es: 'Resultado real', en: 'Real result' },
  'bracket.scorePens': { es: 'Resultado real — decidido en penaltis', en: 'Real result — decided on penalties' },

  // ── Groups ──
  'groups.intro': { es: 'Clasificación **real** + predicción de cada partido.', en: '**Real** standings + prediction for every match.' },
  'groups.legendResult': { es: 'acierto del resultado (1·X·2)', en: 'result hit (1·X·2)' },
  'groups.legendPending': { es: 'por jugar', en: 'to play' },
  'groups.group': { es: 'Grupo {l}', en: 'Group {l}' },
  'groups.team': { es: 'Selección', en: 'Team' },
  'groups.pj': { es: 'PJ', en: 'P' },
  'groups.gd': { es: 'DG', en: 'GD' },
  'groups.pts': { es: 'Pts', en: 'Pts' },
  'groups.matches': { es: 'Partidos · predicción vs real', en: 'Matches · prediction vs real' },
  'groups.prediction': { es: 'Predicción', en: 'Prediction' },
  'groups.pending': { es: 'Pendiente', en: 'Pending' },

  // ── Favourites ──
  'fav.intro': { es: 'Probabilidad de ganar el Mundial según **{n}** simulaciones Monte Carlo del cuadro completo (partidos restantes + eliminatoria).', en: 'Probability of winning the World Cup from **{n}** Monte Carlo simulations of the full bracket (remaining matches + knockouts).' },
  'fav.team': { es: 'Selección', en: 'Team' },
  'fav.semis': { es: 'Semis', en: 'Semis' },
  'fav.final': { es: 'Final', en: 'Final' },
  'fav.champion': { es: 'Campeón', en: 'Champion' },
  'fav.group': { es: 'Grupo {g}', en: 'Group {g}' },

  // ── PredictionPanel ──
  'pred.empty': { es: 'Pulsa un partido del cuadro para ver la predicción', en: 'Tap a match in the bracket to see the prediction' },
  'pred.tie': { es: 'Predicción del cruce', en: 'Match prediction' },
  'pred.final': { es: 'Final proyectada', en: 'Projected final' },
  'pred.title': { es: 'Predicción', en: 'Prediction' },
  'pred.close': { es: 'Cerrar predicción', en: 'Close prediction' },
  'pred.xg': { es: 'Goles esperados (xG)', en: 'Expected goals (xG)' },
  'pred.noFav': { es: 'El modelo no da un favorito claro', en: 'No clear favourite' },
  'pred.favLine': { es: 'favorito **{t}** · confianza {c}%', en: 'favourite **{t}** · confidence {c}%' },
  'pred.result': { es: 'Resultado del partido', en: 'Match result' },
  'pred.draw': { es: 'Empate', en: 'Draw' },
  'pred.scores': { es: 'Marcadores más probables', en: 'Most likely scores' },
  'pred.scoresNote': { es: '· ninguno domina (fútbol = pocos goles)', en: '· none dominates (football = few goals)' },
  'pred.trained': { es: 'Modelo Elo + Poisson entrenado con {n} partidos internacionales reales (hasta {d})', en: 'Elo + Poisson model trained on {n} real international matches (through {d})' },

  // ── Accuracy ──
  'acc.computing': { es: 'Calculando backtest…', en: 'Computing backtest…' },
  'acc.unavailable': { es: 'No disponible aún. Inténtalo en unos segundos.', en: 'Not available yet. Try again in a few seconds.' },
  'acc.honest': { es: '**Validación honesta (out-of-sample).** Se reentrenó el modelo con {train} partidos **excluyendo el Mundial 2026** (sin fuga de datos) y se predijeron los {n} partidos del Mundial 2026 ya jugados (grupos y eliminatorias). Se actualiza solo según se juegan. Así se mide cómo lo haría con partidos que nunca vio.', en: '**Honest out-of-sample validation.** The model was retrained on {train} matches **excluding the 2026 World Cup** (no data leakage) and used to predict the {n} 2026 World Cup matches already played (groups and knockouts). It updates as matches are played, measuring how it would do on matches it never saw.' },
  'acc.generalise': { es: '¿Generaliza? Últimos 3 Mundiales', en: 'Does it generalise? Last 3 World Cups' },
  'acc.globalLine': { es: '{a}% global · {n} partidos', en: '{a}% overall · {n} matches' },
  'acc.baselineElo': { es: 'Elo {b}% · {n} part.', en: 'Elo {b}% · {n} m.' },
  'acc.multiNote': { es: 'Cada Mundial se predice reentrenando **solo con partidos anteriores** a ese torneo. 2022 fue atípico (muchas sorpresas); mostrarlo tal cual es parte de la honestidad del backtest.', en: 'Each World Cup is predicted retraining **only on matches before** that tournament. 2022 was an outlier (many upsets); showing it as-is is part of the backtest’s honesty.' },
  'acc.mAccuracy': { es: 'Acierto resultado (1X2)', en: 'Result accuracy (1X2)' },
  'acc.mAccuracySub': { es: 'local {h}% · mejor Elo {e}%', en: 'home {h}% · higher Elo {e}%' },
  'acc.mExact': { es: 'Marcador exacto', en: 'Exact score' },
  'acc.mExactSub': { es: 'clavar el resultado es casi azar', en: 'nailing the score is near chance' },
  'acc.mBrierSub': { es: 'sin info: {b}', en: 'no-info: {b}' },
  'acc.calTitle': { es: 'Calibración de las probabilidades', en: 'Probability calibration' },
  'acc.calDesc': { es: 'Cada punto agrupa las predicciones por nivel de confianza y las compara con lo que pasó de verdad. Cuanto más pegados a la **diagonal**, mejor calibrado: cuando el modelo dice **60 %**, ese resultado ocurre en torno al **60 %** de las veces. El tamaño del punto es el número de casos en ese tramo.', en: 'Each point groups predictions by confidence level and compares them with what actually happened. The closer to the **diagonal**, the better calibrated: when the model says **60%**, that outcome occurs about **60%** of the time. Point size is the number of cases in that bin.' },
  'acc.calX': { es: 'probabilidad predicha (%)', en: 'predicted probability (%)' },
  'acc.calY': { es: 'frecuencia real (%)', en: 'observed frequency (%)' },
  'acc.calTipPred': { es: 'Predijo ≈**{p}%**', en: 'Predicted ≈**{p}%**' },
  'acc.calTipObs': { es: 'ocurrió el **{o}%** · {n} casos', en: 'occurred **{o}%** · {n} cases' },
  'acc.value': { es: 'El valor del modelo está en **acertar el resultado y calibrar bien las probabilidades**: cuando dice 60%, acierta ~60% de las veces. Clavar el marcador exacto es casi imposible en fútbol ({x}%); el marcador que ves es el **más probable**. Error medio de goles: {mae} por equipo.', en: 'The model’s value is in **getting the result right and calibrating probabilities well**: when it says 60%, it is right ~60% of the time. Nailing the exact score is nearly impossible in football ({x}%); the score shown is the **most likely** one. Mean goal error: {mae} per team.' },
  'acc.tableTitle': { es: 'Predicho vs real · {n} partidos', en: 'Predicted vs real · {n} matches' },
  'acc.colMatch': { es: 'Partido', en: 'Match' },
  'acc.colPred': { es: 'Pred', en: 'Pred' },
  'acc.colReal': { es: 'Real', en: 'Real' },
  'acc.colProb': { es: 'Prob 1/X/2', en: 'Prob 1/X/2' },

  // ── FinalReport ──
  'rep.over': { es: 'El Mundial 2026 ha terminado', en: 'The 2026 World Cup is over' },
  'rep.sub': { es: 'Informe final del modelo: qué predijo antes de cada ronda y qué pasó de verdad.', en: 'The model’s final report: what it predicted before each round and what actually happened.' },
  'rep.champModel': { es: 'Campeón según el modelo', en: 'Champion per the model' },
  'rep.champModelProb': { es: '{p}% de probabilidad de título (la más alta)', en: '{p}% title probability (the highest)' },
  'rep.champReal': { es: 'Campeón real', en: 'Actual champion' },
  'rep.hit': { es: 'El modelo acertó el campeón del Mundial.', en: 'The model called the World Cup champion.' },
  'rep.miss': { es: 'El campeón real no fue el favorito del modelo.', en: 'The actual champion was not the model’s favourite.' },
  'rep.perf': { es: 'Rendimiento sobre los {n} partidos del torneo', en: 'Performance over the tournament’s {n} matches' },
  'rep.oos': { es: 'Validación **out-of-sample**: el modelo se reentrenó excluyendo el Mundial 2026, así que ninguno de estos partidos influyó en sus parámetros.', en: '**Out-of-sample** validation: the model was retrained excluding the 2026 World Cup, so none of these matches influenced its parameters.' },
  'rep.byRound': { es: 'Aciertos del cuadro por ronda', en: 'Bracket hits by round' },
  'rep.hitsLabel': { es: '**Cruces acertados** — ¿predijo el modelo este emparejamiento exacto? Total: ', en: '**Matchups hit** — did the model predict this exact pairing? Total: ' },
  'rep.favLabel': { es: '**El favorito pasó** — en los cruces reales, ¿avanzó el equipo que el modelo daba por favorito? Total: ', en: '**Favourite advanced** — in the real ties, did the model’s favourite go through? Total: ' },
  'rep.chainNote': { es: 'Acertar el cruce exige acertar en cadena todos los partidos anteriores, por eso baja en rondas avanzadas.', en: 'Hitting a matchup requires getting every prior match right in a chain, so it drops in later rounds.' },
  'rep.goBracket': { es: 'Ver el cuadro completo real vs predicho', en: 'See the full real vs predicted bracket' },

  // ── HowItWorks ──
  'how.intro': { es: 'Nada de esta web está inventado: cada probabilidad sale de un modelo estadístico entrenado con **{n} partidos internacionales oficiales desde 1872**. Así funciona, de los datos a la predicción.', en: 'Nothing here is made up: every probability comes from a statistical model trained on **{n} official international matches since 1872**. Here is how it works, from data to prediction.' },
  'how.s1t': { es: 'Datos reales', en: 'Real data' },
  'how.s1': { es: 'Resultados oficiales (martj42/international_results): 154 años de partidos con torneo, sede y marcador. Se actualizan solos tras cada jornada.', en: 'Official results (martj42/international_results): 154 years of matches with tournament, venue and score. They update automatically after each matchday.' },
  'how.s2t': { es: 'Elo: fuerza global', en: 'Elo: overall strength' },
  'how.s2': { es: 'Se procesa toda la historia en orden. Ganar sube tu rating según la dificultad del rival, la importancia del torneo y la diferencia de goles.', en: 'The full history is processed in order. Winning raises your rating based on opponent strength, tournament importance and goal difference.' },
  'how.s3t': { es: 'Poisson: goles esperados', en: 'Poisson: expected goals' },
  'how.s3': { es: 'Un GLM (scikit-learn) aprende el ataque y la defensa de cada selección, pesando más lo reciente y los Mundiales. De ahí salen los xG y la matriz de marcadores.', en: 'A GLM (scikit-learn) learns each team’s attack and defence, weighting recent and World Cup matches more. This yields the xG and the score matrix.' },
  'how.s4t': { es: 'Monte Carlo: el torneo', en: 'Monte Carlo: the tournament' },
  'how.s4': { es: 'Se simula el cuadro completo 40.000 veces partido a partido (prórroga y penaltis incluidos). Las probabilidades son frecuencias de esas simulaciones.', en: 'The full bracket is simulated 40,000 times match by match (extra time and penalties included). Probabilities are frequencies over those simulations.' },
  'how.eloTitle': { es: 'La fuerza de cada selección, entrenada sobre 154 años', en: 'Each team’s strength, trained over 154 years' },
  'how.eloSub': { es: 'Rating Elo al cierre de cada año — las 5 selecciones más fuertes hoy. Pasa el ratón para comparar cualquier año.', en: 'Elo rating at each year-end — the 5 strongest teams today. Hover to compare any year.' },
  'how.heatTitle': { es: 'De dos equipos a un marcador: la matriz Poisson', en: 'From two teams to a score: the Poisson matrix' },
  'how.heatSub': { es: 'Probabilidad de cada marcador exacto en {a} – {b} según los goles esperados del modelo. Ningún marcador supera ~el 12%: por eso el titular son las probabilidades, no "el resultado".', en: 'Probability of each exact score in {a} – {b} from the model’s expected goals. No score exceeds ~12%: that is why the headline is the probabilities, not "the result".' },
  'how.heatRows': { es: 'Goles de **{a}** (filas) × goles de **{b}** (columnas) · xG {xa} – {xb}', en: 'Goals by **{a}** (rows) × goals by **{b}** (columns) · xG {xa} – {xb}' },
  'how.heatProb': { es: 'probabilidad {v}%', en: 'probability {v}%' },
  'how.mcTitle': { es: '40.000 Mundiales simulados', en: '40,000 simulated World Cups' },
  'how.mcSub': { es: 'Probabilidad de título: en cuántas de las 40.000 simulaciones cada selección acaba levantando la copa.', en: 'Title probability: in how many of the 40,000 simulations each team lifts the cup.' },
  'how.barTip': { es: 'octavos {r16}% · cuartos {qf}%', en: 'R16 {r16}% · QF {qf}%' },
  'how.barTip2': { es: 'semis {sf}% · final {f}%', en: 'SF {sf}% · final {f}%' },
  'how.barTip3': { es: 'campeón {c}%', en: 'champion {c}%' },
  'how.valTitle': { es: 'Validación honesta', en: 'Honest validation' },
  'how.valSub': { es: 'El modelo se evalúa reentrenándolo SIN los partidos del Mundial 2026 y prediciendo lo que nunca vio (out-of-sample). Sin fuga de datos: la métrica que ves es la que tendría en la vida real.', en: 'The model is evaluated by retraining it WITHOUT the 2026 World Cup matches and predicting what it never saw (out-of-sample). No data leakage: the metric you see is what it would achieve in real life.' },
  'how.valBtn': { es: 'Ver la precisión medida partido a partido', en: 'See the accuracy measured match by match' },
}
